name: Terraform CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - '*.tf'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '*.tf'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

env:
  TERRAFORM_VERSION: '1.12.2'
  WORKING_DIRECTORY: '.'
  RESOURCE_GROUP_NAME: 'MC'
  STORAGE_ACCOUNT_NAME: 'mctf'
  CONTAINER_NAME: 'tfstate'
  BACKEND_KEY: 'terraform.tfstate'

jobs:
  validate:
    name: 'Validate Terraform'
    runs-on: ubuntu-latest
    environment: terraform-secrets
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ env.CONTAINER_NAME }}" \
          -backend-config="key=${{ env.BACKEND_KEY }}" \
          -backend-config="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}"
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: 🤖 AI Analysis of Terraform Plan
      run: python scripts/analyze-terraform-plan.py
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        AZURE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
        AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
      continue-on-error: true

    - name: Upload AI Analysis Report
      uses: actions/upload-artifact@v4
      with:
        name: ai-analysis-report
        path: ${{ env.WORKING_DIRECTORY }}/terraform-analysis.txt
        retention-days: 30
      if: always()

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: ${{ env.WORKING_DIRECTORY }}/tfplan
        retention-days: 30
